version: '3.8'

services:
  media_service:
    image: media
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - .:/media_files
    command: ["python", "manage.py", "runserver", "8003"]
    container_name: media_service
    restart: unless-stopped
    networks:
      - wikiculture_network
    environment:        # Add environment variables here
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  consumer:
    image: media
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python","consumer.py"]
    restart: unless-stopped
    depends_on:
      - media_service
    networks:
      - wikiculture_network
    environment:        # Add environment variables here
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

networks: 
  wikiculture_network:
    driver: bridge
