version: '3.8'

services:
  media_servicea:
    image: media
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8003:8003"
    command: ["python", "manage.py", "runserver", "8003"]
    container_name: media_service
    restart: unless-stopped
    networks:
      - bridge

  consumer:
    image: media
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python","consumer.py"]
    restart: unless-stopped
    depends_on:
      - media_service
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
    name: bridge