version: '3.8'

services:
  comment_service:
    image: comment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    command: ["python", "manage.py", "runserver", "8002"]
    container_name: comment_service
    restart: unless-stopped
    networks:
      - common_network
    volumes:
      - .:/comments

  consumer:
    image: comment
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python","consumer.py"]
    restart: unless-stopped
    depends_on:
      - comment_service
    networks:
      - common_network

networks: 
  common_network:
    driver: bridge