apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles-service
  template:
    metadata:
      labels:
        app: articles-service
    spec:
      containers:
        - name: articles-service
          image: ghcr.io/tomdieu/wikiculture/article_service:latest
          ports:
            - containerPort: 8001
          command: ["python", "manage.py", "runserver", "8001"]

          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: rabbitmq-config
            - configMapRef:
                name: wikiculture-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "250m"
        - name: consumer
          image: ghcr.io/tomdieu/wikiculture/article_service:latest
          command: ["python", "consumer.py"]

          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: articles-service
spec:
  selector:
    app: articles-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
