apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles-service
  template:
    metadata:
      labels:
        app: articles-service
    spec:
      volumes:
        - name: articles-static-volume
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: ghcr.io/tomdieu/wikiculture/article_service:latest
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          imagePullPolicy: "IfNotPresent"
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          volumeMounts:
            - name: articles-static-volume
              mountPath: /articles
      containers:
        - name: articles-service
          image: ghcr.io/tomdieu/wikiculture/article_service:latest
          ports:
            - containerPort: 8001
          command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
          imagePullPolicy: "IfNotPresent"

          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: rabbitmq-config
            - configMapRef:
                name: wikiculture-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: articles-static-volume
              mountPath: /articles
        - name: consumer
          image: ghcr.io/tomdieu/wikiculture/article_service:latest
          command: ["python", "consumer.py"]
          imagePullPolicy: "IfNotPresent"

          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: articles-service
spec:
  selector:
    app: articles-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
