apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator-service
  template:
    metadata:
      labels:
        app: moderator-service
    spec:
      volumes:
        - name: moderator-static-volume
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: ghcr.io/tomdieu/wikiculture/moderator_service:latest
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          imagePullPolicy: "IfNotPresent"
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: rabbitmq-config
            - configMapRef:
                name: wikiculture-config
          volumeMounts:
            - name: moderator-static-volume
              mountPath: /moderator/staticfiles
      containers:
        - name: moderator-service
          image: ghcr.io/tomdieu/wikiculture/moderator_service:latest
          ports:
            - containerPort: 8005
          command: ["python", "manage.py", "runserver", "0.0.0.0:8005"]
          imagePullPolicy: "IfNotPresent"

          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "300m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          volumeMounts:
            - name: moderator-static-volume
              mountPath: /moderator/staticfiles
        - name: consumer
          image: ghcr.io/tomdieu/wikiculture/moderator_service:latest
          command: ["python", "consumer.py"]
          imagePullPolicy: "IfNotPresent"

          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "300m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: moderator-service
spec:
  selector:
    app: moderator-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
