apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      volumes:
        - name: search-static-volume
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: ghcr.io/tomdieu/wikiculture/search_service:latest
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: elastic-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
          volumeMounts:
            - name: search-static-volume
              mountPath: /search/staticfiles
      containers:
        - name: search-service
          image: ghcr.io/tomdieu/wikiculture/search_service:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8004
          command: ["python", "manage.py", "runserver", "0.0.0.0:8004"]
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "300m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          envFrom:
            - configMapRef:
                name: elastic-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
            - configMapRef:
                name: wikiculture-config
          volumeMounts:
            - name: search-static-volume
              mountPath: /search/staticfiles
        - name: consumer
          image: ghcr.io/tomdieu/wikiculture/search_service:latest
          command: ["python", "consumer.py"]
          imagePullPolicy: "IfNotPresent"

          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "1000m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "1000m"
          envFrom:
            - configMapRef:
                name: elastic-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
