apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: ghcr.io/tomdieu/wikiculture/search_service:latest
          ports:
            - containerPort: 8004
          command: ["python", "manage.py", "runserver", "0.0.0.0:8004"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "400m"
            limits:
              memory: "256Mi"
              cpu: "550m"
          envFrom:
            - configMapRef:
                name: elastic-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
        - name: consumer
          image: ghcr.io/tomdieu/wikiculture/search_service:latest
          command: ["python", "consumer.py"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: elastic-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
