version: '3.8'

services:

  web:

    image: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: client_service
    volumes:
      - .:/client
    networks:
      - bridge

networks:
    bridge:
        driver: bridge