apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user
          ports:
            - containerPort: 8000
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          volumeMounts:
            - name: user-volume
              mountPath: /users
          envFrom:
            - secretRef:
                name: rabbitmq-secret
            - configMapRef:
                name: user-service-env
      volumes:
        - name: user-volume
          emptyDir: {}
