apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: ghcr.io/tomdieu/wikiculture/search_service:latest
          ports:
            - containerPort: 8004
          command: ["python", "manage.py", "runserver", "0.0.0.0:8004"]
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: elastic-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
        - name: consumer
          image: ghcr.io/tomdieu/wikiculture/search_service:latest
          command: ["python", "consumer.py"]
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: elastic-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
