version: '3.8'

services:

  user_service:
    image: user
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/users
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "8000"]
    container_name: user_service
    networks:
      - common_network

networks: 
  common_network:
    driver: bridge