version: '3.8'

services:

  user_service:
    image: user
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "8000"]
    container_name: user_service
    networks:
      - bridge

networks: 
  bridge:
    driver: bridge
    name: bridge