# Generated by Django 5.0.1 on 2024-02-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_description_category_is_cultural_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
