# Generated by Django 5.0.4 on 2024-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_article_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
