# Generated by Django 5.0.4 on 2024-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_culturalarea_region_village_article_village_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlevistors",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
