# Generated by Django 5.0.4 on 2024-05-20 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_articlevistors_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="cultural_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="api.culturalarea",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="villages",
                to="api.region",
            ),
        ),
    ]
