# Generated by Django 5.0.4 on 2024-05-31 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_articlevistors_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='cultural_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_area', to='api.culturalarea'),
        ),
        migrations.AlterField(
            model_name='village',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='api.region'),
        ),
    ]
