# Generated by Django 5.0.4 on 2024-06-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_region_cultural_area_alter_village_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingtime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
