# Generated by Django 5.0.4 on 2024-06-02 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_readingtime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevistors',
            name='user_agent',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
