# Generated by Django 5.0.4 on 2024-06-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_articlelike_ip_address_articlelike_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together={('article', 'user', 'ip_address', 'user_agent')},
        ),
    ]
