# Generated by Django 5.0.4 on 2024-06-03 22:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalarea',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
