# Generated by Django 5.0.4 on 2024-06-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_userarticleinteraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="CulturalSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_percentage", models.FloatField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities",
                        to="api.article",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities",
                        to="api.village",
                    ),
                ),
            ],
            options={
                "unique_together": {("article", "village")},
            },
        ),
    ]
