# Generated by Django 5.0.4 on 2024-06-11 19:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_culturalsimilarity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, default="", null=True),
        ),
        migrations.CreateModel(
            name="ArticleAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keywords", models.JSONField()),
                ("named_entities", models.JSONField()),
                ("sentiment", models.JSONField()),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="api.article",
                    ),
                ),
            ],
        ),
    ]
