version: '3.8'

services:
  notification_service:
    image: notification
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8006"]
    container_name: notification_service
    volumes:
      - .:/notifications
    environment:        # Add environment variables here
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - USER_SERVICE=user_service 

  consumer:
    image: notification
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python","consumer.py"]
    depends_on:
      - notification_service
    environment:        # Add environment variables here
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672