version: '3.8'

services:
  notification_service:
    image: notification
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    command: ["python", "manage.py", "runserver", "8006"]
    container_name: notification_service
    networks:
      - bridge
    volumes:
      - .:/notifications

  consumer:
    image: notification
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python","consumer.py"]
    depends_on:
      - notification_service
    networks:
      - common_network

networks: 
  common_network:
    driver: bridge