version: '3.8'

services:
  moderator_service:
    image: moderator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8005"]
    container_name: moderator_service
    restart: unless-stopped
    networks:
      - wikiculture_network
    volumes:
      - .:/moderator
    environment:        # Add environment variables here
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  consumer:
    image: moderator
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python","consumer.py"]
    restart: unless-stopped
    depends_on:
      - moderator_service
    networks:
      - wikiculture_network
    environment:        # Add environment variables here
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

networks: 
  wikiculture_network:
    driver: bridge
