# Generated by Django 5.0.1 on 2024-04-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Image', 'Image'), ('Document', 'Document'), ('Audio', 'Audio'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
