# Generated by Django 5.0.1 on 2024-05-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_bio_userpasswordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasswordresettoken',
            name='reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
