# Generated by Django 5.0.1 on 2024-05-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('default', 'default'), ('article', 'article')], default='article', max_length=20),
        ),
    ]
