# Generated by Django 5.0.1 on 2024-05-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('default', 'default'), ('article_approved', 'article_approved'), ('article_rejected', 'article_rejected')], default='article', max_length=20),
        ),
    ]
