version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: RabbitMq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      # AMQ protocol port
      - "5672:5672"
      # Http Managent UI
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

    networks:
      - common_network
    extra_hosts:
      - host.docker.internal:host-gateway

networks: 
  common_network:
    driver: bridge