# Generated by Django 5.0.1 on 2024-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderationrecord',
            old_name='user',
            new_name='moderator',
        ),
        migrations.AlterField(
            model_name='moderationrecord',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
