# Generated by Django 5.0.1 on 2024-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='village',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
